language: java
script: make release
before_script:
  - export VERSION=`grep log4jplugin.version plugin.properties | cut -d'=' -f2`
cache:
  directories:
  - "$HOME/.m2"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PBmuG0tqMdgx7wihSh37BWg0JBNbAbj0F1aHsAOsUR6NRQV3Wt8s1V0ocR5Xrt0jJ2BGD2K4IYEu+AE05FSKijzst2K3lWJENN2KuFnwLv9W0LQfcv7MaM18ocSaGyFV83zErKCQbR4VjW8LOXoOs7lLzAll78wvoWPw/446IVBeC1USo6fuO4ojh3/culqzNUKZnnlL0EjalW0h6P0q13D5g38JL5RdTfOpTF/ViwsGswTLtHxn4m3remxmUmBoYytnnM/LCLhT1AHUI9j7aUpIU8W6JZXTMjQf/RvcHT57JByktzipz9RAkIQHfCZLKQI/FTrNmOVFQSgK0W74KXmyIPnQJQTxBKzacjXt8EW6ZflilYsmZJJv5oTrVLuUMyzCHSafTK3vo35vZELLK+PzxG4FYeqZqO3XTHR8feCoyoRThnbRazTy/dMu1cYxrXNzZnJvBkQgBH6eu3LpqrylXM3wAKBP7YG6rXnPWUj9VnnUEvaQ8t3UJQS8p23o2jbZ9S8CQuxx/EVRouIgJe5chNESGiFVz0ZirNYQApMJjXmY9edUUE0JnR0dYZ92Dvuevase8+2/7ZaF4nAvqIW9bI/n61nnBFaHgAyzz4KbJ79+dLX+AjIZpxzK+TbQ1bQVa8zSlO4V8EouZ6AaSXYvYw3oT4GlxRnfc+WiyiI=
  file: release/log4j-plugin-fluency-${VERSION}-jar-with-dependencies.jar
  on:
    tags: true
notifications:
  slack:
    secure: WTSX79qW1fZKPyB/vJ131q3stiHB2RcHTLZz1+lE+8strIvyLHXLwyM3QNfLRVivBXlJ7AM0rBu0FzpUuhq5vDQZHs4gf8ZTql5qB0p/KUbzVmD1dQnIjhAeRFRkynoBDOvJEt3TZhAcTeTnjQVwlS9DfvRz6BycvmC1MNngZiNJHme8uN7e+XnjgQWyuvi9YumLL40YIJQb6WOOlTRF8iufqdaMNiqK+kPGe5Twm+Nx9VBymI9TcFtYk2JWWqokr+yUsTORSkVk+cxMQoZOAFZcKxoO/ZiSOOrJOMPgBjKOQuWTy27xqSQ9rXmeL6RF2g+C0YdAMxp09DjG7d6LEZcwvo/jbPYOcluy3JcZthIlQTyZxOIKea1CPYlE/rlm5qT55BI5OMAWo44rFvQ0gp0KbESBOQAw+BHsf/jVjMerBMQHlxYiZqAcA6Sn8kJ+tlz9qMlFQUDT4YWIyvyGTGG/335mOniZU7cvyrMNET5y0o9yVgD7YFZyZLESrPo9lQ75Cb980ARkuYMq6skfw01YA98SmiBj1UMVRNQWKEgok8Bt7Gogu+Ob5A6KWWAshZ2d8KsuxH3bLid20860teGLwwfduLTyTcEvGslVNK5qsuA4os5R69EgWaDgdRNGnLhE4RbpexDsH1mPwJMeb5c1ZCfYWCqyTpdAYJMZgg0=
